name: Tag release
on:
  pull_request:

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Store version number
        run: echo "${{ github.ref }}" > new_tag
      - name: Upload version number
        uses: actions/upload-artifact@v3
        with:
          name: new_tag
          path: new_tag
